import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Inter, Mulish } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: "swap"
})

export const metadata = {
  title: 'E-Commerce Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}

